Algoritmo "problema-consumo"

Var

   distanciaPercorrida: real
   combustivelGasto: real
   consumoMedio: real


Inicio

      escreva("Distancia percorrida: ")
      leia(distanciaPercorrida)
      escreva("Combustível gasto: ")
      leia(combustivelGasto)
      escreval()
      consumoMedio <- distanciaPercorrida / combustivelGasto
      escreva("Consumo médio: ", consumoMedio:2:3)

Fimalgoritmo

